/**
 * Indian legal document format categories.
 * Sourced from /formats/start.txt
 */
export const FORMAT_CATEGORIES = [
  { name: 'Agreement', description: 'A formal contract outlining mutual rights and obligations between parties.' },
  { name: 'Application', description: 'A written request submitted to an authority seeking specific relief or approval.' },
  { name: 'Appointment', description: 'A document designating an individual to a specific role or position.' },
  { name: 'Apprenticeship', description: 'An agreement defining training terms between an employer and trainee.' },
  { name: 'Arbitration', description: 'A document establishing terms for resolving disputes outside court.' },
  { name: 'Assignment', description: 'Transfers rights, interests, or obligations from one party to another.' },
  { name: 'Banking', description: 'Legal formats for loans, guarantees, securities, and financial transactions.' },
  { name: 'Bond', description: 'A binding instrument for repayment or performance of an obligation.' },
  { name: 'Civil Pleadings', description: 'Documents initiating or responding to civil court proceedings.' },
  { name: 'Classification of Offences', description: 'Legal categorization of crimes by nature and severity.' },
  { name: 'Company', description: 'Corporate documents including incorporation, resolutions, and filings.' },
  { name: 'Composition Deed', description: 'Agreement between debtor and creditors for debt settlement.' },
  { name: 'Consumer Protection Act', description: 'Legal formats for consumer complaints and redressal.' },
  { name: 'Conveyancing', description: 'Documents for transferring ownership or interest in property.' },
  { name: 'Copyright', description: 'Legal instruments protecting creative and intellectual works.' },
  { name: 'Criminal Pleading', description: 'Formats for complaints, charge-sheets, and defense statements.' },
  { name: 'Easements', description: 'Documents granting or recognizing usage rights over another\'s land.' },
  { name: 'Exchange', description: 'Deeds transferring ownership of properties mutually between parties.' },
  { name: 'Franchisee', description: 'Agreement outlining rights and obligations in a business franchise.' },
  { name: 'Gift', description: 'A deed transferring property voluntarily without consideration.' },
  { name: 'Guarantee', description: 'A commitment ensuring fulfillment of another\'s obligation.' },
  { name: 'Hire Purchase', description: 'Agreement allowing asset use with eventual ownership on payment.' },
  { name: 'Income Tax', description: 'Formats for declarations, appeals, and compliance under tax law.' },
  { name: 'Indemnity', description: 'Contract protecting one party against potential financial loss.' },
  { name: 'Information Technology', description: 'Legal documents for digital contracts, data, and cyber laws.' },
  { name: 'Infrastructure', description: 'Agreements related to development and operation of public assets.' },
  { name: 'Labour', description: 'Formats for employment, wages, disputes, and compliance matters.' },
  { name: 'Lease Financing', description: 'Documents for leasing assets or financing their acquisition.' },
  { name: 'Matrimonial', description: 'Legal formats for marriage, divorce, maintenance, and custody.' },
  { name: 'Medical Form', description: 'Documents for consent, liability, and medical reporting.' },
  { name: 'Memorandum of Understanding', description: 'Preliminary agreement outlining intent for cooperation.' },
  { name: 'Miscellaneous Deeds', description: 'Other legal instruments not covered under specific heads.' },
  { name: 'Mortgage Pledge Hypothecation', description: 'Security documents for loans against assets.' },
  { name: 'Motor Vehicle Act', description: 'Legal forms for claims, licenses, and transport regulation.' },
  { name: 'Negotiable Instrument', description: 'Formats for promissory notes, bills, and cheques.' },
  { name: 'Notice', description: 'Formal communication asserting rights or demanding action.' },
  { name: 'Partition', description: 'Deeds dividing property among co-owners or heirs.' },
  { name: 'Partnership', description: 'Agreements defining partners\' rights, duties, and profit sharing.' },
  { name: 'Petition', description: 'Formal written plea to a court or authority seeking relief.' },
  { name: 'Plaint and Written Statement', description: 'Initial claim and defense documents in civil suits.' },
  { name: 'Pleadings', description: 'Written submissions presenting claims and defenses in court.' },
  { name: 'Power of Attorney', description: 'Authorizes another person to act on one\'s behalf legally.' },
  { name: 'Principle', description: 'Foundational legal concepts or doctrines guiding interpretation.' },
  { name: 'Release', description: 'Document relinquishing rights, claims, or interests voluntarily.' },
  { name: 'Rent', description: 'Agreements specifying terms of tenancy and property occupation.' },
  { name: 'Sale', description: 'Deed transferring ownership of property for consideration.' },
  { name: 'Specific Relief Act', description: 'Legal formats for enforcement of rights and contracts.' },
  { name: 'Trust Wakf Society', description: 'Documents creating or governing trusts, wakfs, and societies.' },
  { name: 'Vakalatnama', description: 'Authorization for an advocate to represent a client in court.' },
  { name: 'Will', description: 'Legal declaration of a person\'s wishes regarding property after death.' },
]
